LaunchFolderSelect:$.minecraft\
LaunchVersionSelect:魔戒MC社区整合包（1.7.10）
LoginPageType:0
LaunchArgumentTitle:魔戒MC社区整合包 1.7.10   当前时间：{time}
LaunchRamType:0
LaunchRamCustom:28
LaunchArgumentWindowType:2
UiLauncherTransparent:600
UiLauncherTheme:0
UiLauncherLogo:True
UiBackgroundColorful:True
UiMusicAuto:True
UiHiddenOtherFeedback:False
UiHiddenOtherHelp:False
SystemSystemUpdate:1
SystemSystemActivity:0
LaunchAdvanceAssets:True
LaunchAdvanceJava:False
WindowHeight:655
WindowWidth:1040
LaunchArgumentIndieV2:0
